### ISSUE TITLE
Traffic Display Functionality Request

### ISSUE THREAD

**Issue by skijeffory** [markcellis/X-Camera#10]
I would like the ability to be able to sort the display based on Callsign instead of From Airport/From Aircraft.  I was hosting a virtual Airshow on VATSIM over the weekend, and it was problematic to 1) find the callsign requesting focus and 2) clicking it as they were flying since the tailnumber was climbing up/down the list at a rapid pace.

**Comment by markcellis** [comment]
This is complete and will be released in X-Camera 2.4.4 Beta 3
