### ISSUE TITLE
Make "toggle zoom lock" permanent

### ISSUE THREAD

**Issue by BitBarrel** [markcellis/X-Camera#4]
Please add an option to make "middle mouse behavior -> toggle zoom lock" permanent instead of having to press the middle mouse button before the zoom lock feature works.

**Comment by markcellis** [comment]
I thought the camera option, Disable Cockpit Zoom, would make it permanent on a camera. Can you expand on why this feature does not meet your needs?

![Capture](https://user-images.githubusercontent.com/25938986/205274966-70b1331c-abfb-4921-9858-c87ad5ecc93c.JPG)

**Comment by BitBarrel** [comment]
Yes, I need to permanently disable the scroll zoom on the cockpit camera because I only use the sim with a fixed camera position and angle, never any need to zoom. No need to look around the cockpit too. It is for a training scenario during the descent only. I find that students often accidentally zoom instead of rotating a switch on the A320 FCU, hence I need to permanently disable it.

I guess clicking the middle mouse button will do too, but every time I have to remember to do that when I start the sim.

**Comment by markcellis** [comment]
> Yes, I need to permanently disable the scroll zoom on the cockpit camera because I only use the sim with a fixed camera position and angle, never any need to zoom. No need to look around the cockpit too. It is for a training scenario during the descent only. I find that students often accidentally zoom instead of rotating a switch on the A320 FCU, hence I need to permanently disable it.
> 
> I guess clicking the middle mouse button will do too, but every time I have to remember to do that when I start the sim.

I understand the need but what I wanted to know is if you had tried the "Disable Cockpit Zoom" option on the camera setting. I think that does what you want. If it isn't working or there is some other missing capability let me know.

**Comment by BitBarrel** [comment]
Ah, I see. I didn't know there was already an option to permanently disable the scroll zoom. 

I tested it and it did work :-)

**Comment by markcellis** [comment]
Great, I will mark this as closed.
